"""Init conversation table

Revision ID: 96976ba2f9aa
Revises: 
Create Date: 2026-03-06 17:56:05.158326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96976ba2f9aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_schema'
    )
    op.create_index(op.f('ix_agent_schema_conversations_id'), 'conversations', ['id'], unique=False, schema='agent_schema')
    op.create_index(op.f('ix_agent_schema_conversations_user_id'), 'conversations', ['user_id'], unique=False, schema='agent_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_schema_conversations_user_id'), table_name='conversations', schema='agent_schema')
    op.drop_index(op.f('ix_agent_schema_conversations_id'), table_name='conversations', schema='agent_schema')
    op.drop_table('conversations', schema='agent_schema')
    # ### end Alembic commands ###
