"""create missing knowledge logs table

Revision ID: a473039c3ecc
Revises: 96976ba2f9aa
Create Date: 2026-03-31 22:03:18.622257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a473039c3ecc'
down_revision: Union[str, None] = '96976ba2f9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_knowledge_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_schema'
    )
    op.create_index(op.f('ix_agent_schema_missing_knowledge_logs_id'), 'missing_knowledge_logs', ['id'], unique=False, schema='agent_schema')
    op.create_index(op.f('ix_agent_schema_missing_knowledge_logs_thread_id'), 'missing_knowledge_logs', ['thread_id'], unique=False, schema='agent_schema')
    op.create_index(op.f('ix_agent_schema_missing_knowledge_logs_user_id'), 'missing_knowledge_logs', ['user_id'], unique=False, schema='agent_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_schema_missing_knowledge_logs_user_id'), table_name='missing_knowledge_logs', schema='agent_schema')
    op.drop_index(op.f('ix_agent_schema_missing_knowledge_logs_thread_id'), table_name='missing_knowledge_logs', schema='agent_schema')
    op.drop_index(op.f('ix_agent_schema_missing_knowledge_logs_id'), table_name='missing_knowledge_logs', schema='agent_schema')
    op.drop_table('missing_knowledge_logs', schema='agent_schema')
    # ### end Alembic commands ###
