import type { LocationRow, RouteRow, Status } from "./MissingInMapTypes";

export const PAGE_SIZE = 5;
export const LOCATION_TOTAL = 42;
export const ROUTE_TOTAL = 24;

export const INITIAL_LOCATIONS: LocationRow[] = [
  {
    rowId: 1,
    id: "#LOC-2104",
    name: "Phòng Nghiên cứu AI",
    buildingName: "Building H6",
    floor: "FL-04",
    requestedBy: "Nguyễn Hoàng Nam",
    requesterRole: "GV",
    adminNote: "Cần xác minh vị trí cửa chính.",
    createdAt: "2023-11-05 08:30",
    status: "PENDING",
  },
  {
    rowId: 2,
    id: "#LOC-2099",
    name: "Văn phòng Đoàn TN",
    buildingName: "Building A1",
    floor: "FL-01",
    requestedBy: "Trần Minh Hải",
    requesterRole: "SV",
    adminNote: "Đang vẽ polygon ranh giới.",
    createdAt: "2023-11-04 14:15",
    status: "IN_PROGRESS",
  },
  {
    rowId: 3,
    id: "#LOC-2088",
    name: "Khu vực Sạc xe điện",
    buildingName: "Nhà xe B4",
    floor: "FL-G",
    requestedBy: "Lê Thị Tuyết",
    requesterRole: "NV",
    adminNote: "Đã cập nhật lên bản đồ live.",
    createdAt: "2023-11-02 09:45",
    status: "REMOVED",
  },
  {
    rowId: 4,
    id: "#LOC-2077",
    name: "Trung tâm Hỗ trợ Sinh viên",
    buildingName: "Building A4",
    floor: "FL-02",
    requestedBy: "Phạm Quỳnh Như",
    requesterRole: "SV",
    adminNote: "Cần kiểm tra trùng lặp với dữ liệu cũ.",
    createdAt: "2023-10-30 11:50",
    status: "PENDING",
  },
  {
    rowId: 5,
    id: "#LOC-2064",
    name: "Phòng Truyền thống",
    buildingName: "Building B1",
    floor: "FL-01",
    requestedBy: "Ngô Đức Hải",
    requesterRole: "GV",
    adminNote: "Ưu tiên xử lý trước tuần lễ tuyển sinh.",
    createdAt: "2023-10-27 09:20",
    status: "PENDING",
  },
  {
    rowId: 6,
    id: "#LOC-2051",
    name: "Điểm đón xe buýt nội khu",
    buildingName: "Cổng chính",
    floor: "FL-G",
    requestedBy: "Đinh Hữu Long",
    requesterRole: "NV",
    adminNote: "Thiếu metadata vị trí biển báo.",
    createdAt: "2023-10-25 16:40",
    status: "IN_PROGRESS",
  },
];

export const INITIAL_ROUTES: RouteRow[] = [
  {
    rowId: 1,
    id: "#RT-0982",
    startPoint: "Cổng B1 - Lý Thường Kiệt",
    startMeta: "BLD-A1 / FL-G",
    endPoint: "Thư viện Trung tâm",
    endMeta: "BLD-LIB / FL-02",
    reason: "Tuyến đường đi bộ tắt giữa A1 và thư viện chưa cập nhật.",
    reportedBy: "Lê Quang Minh",
    reporterRole: "SV",
    createdAt: "2023-10-12 14:30",
    status: "PENDING",
  },
  {
    rowId: 2,
    id: "#RT-0975",
    startPoint: "Phòng Lab 304 - B10",
    startMeta: "BLD-B10 / FL-03",
    endPoint: "Xưởng Cơ khí",
    endMeta: "BLD-C4 / FL-G",
    reason: "Hành lang nối bị chặn do sửa chữa, cần định tuyến lại.",
    reportedBy: "Trần Thị Lan",
    reporterRole: "GV",
    createdAt: "2023-10-11 09:15",
    status: "IN_PROGRESS",
  },
  {
    rowId: 3,
    id: "#RT-0961",
    startPoint: "Cổng sau cư xá",
    startMeta: "CX-01 / FL-G",
    endPoint: "Nhà xe B4",
    endMeta: "BLD-B4 / FL-G",
    reason: "Lối đi mới cho xe máy đã hoàn thành.",
    reportedBy: "Phạm Anh Tuấn",
    reporterRole: "NV",
    createdAt: "2023-10-10 16:45",
    status: "RESOLVED",
  },
  {
    rowId: 4,
    id: "#RT-0955",
    startPoint: "Tòa nhà H6 - Dĩ An",
    startMeta: "BLD-H6 / FL-04",
    endPoint: "Hồ Bơi",
    endMeta: "ZONE-B / FL-G",
    reason: "Thiếu dữ liệu thang máy cho người khuyết tật.",
    reportedBy: "Bùi Minh Khôi",
    reporterRole: "SV",
    createdAt: "2023-10-09 11:20",
    status: "PENDING",
  },
  {
    rowId: 5,
    id: "#RT-0944",
    startPoint: "Nhà thi đấu",
    startMeta: "ZONE-S / FL-G",
    endPoint: "Ký túc xá K2",
    endMeta: "KTX-K2 / FL-G",
    reason: "Bản đồ thiếu đoạn nối qua cổng phụ phía Đông.",
    reportedBy: "Hoàng Đức Anh",
    reporterRole: "SV",
    createdAt: "2023-10-07 19:05",
    status: "PENDING",
  },
  {
    rowId: 6,
    id: "#RT-0939",
    startPoint: "Phòng Y tế",
    startMeta: "BLD-A2 / FL-01",
    endPoint: "Bãi giữ xe nhân viên",
    endMeta: "PARK-ST / FL-G",
    reason: "Thiếu tuyến ưu tiên xe lăn qua ramp mới.",
    reportedBy: "Đào Thanh Vân",
    reporterRole: "NV",
    createdAt: "2023-10-05 10:10",
    status: "IN_PROGRESS",
  },
];

export const STATUS_FILTER_OPTIONS: Array<{ value: "ALL" | Status; label: string }> = [
  { value: "ALL", label: "Tất cả trạng thái" },
  { value: "PENDING", label: "PENDING" },
  { value: "IN_PROGRESS", label: "IN PROGRESS" },
  { value: "RESOLVED", label: "ĐÃ XỬ LÝ" },
  { value: "REMOVED", label: "ĐÃ LOẠI BỎ" },
];
