"""update faq relationship to document version

Revision ID: 95beb4186a30
Revises: 
Create Date: 2026-02-05 14:02:32.622480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95beb4186a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_version', 'document_versions', ['document_id', 'version'])
    op.add_column('faqs', sa.Column('document_version_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_faqs_document_version_id'), 'faqs', ['document_version_id'], unique=False)
    op.drop_constraint(op.f('faqs_document_id_fkey'), 'faqs', type_='foreignkey')
    op.create_foreign_key(None, 'faqs', 'document_versions', ['document_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('faqs', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'faqs', type_='foreignkey')
    op.create_foreign_key(op.f('faqs_document_id_fkey'), 'faqs', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_faqs_document_version_id'), table_name='faqs')
    op.drop_column('faqs', 'document_version_id')
    op.drop_constraint('uq_document_version', 'document_versions', type_='unique')
    # ### end Alembic commands ###
